root: brats_crops
modality: t1
run_name: t1_trial_004_opt-rmsprop_lr-0.001_loss-dice_ce_sch-cosine_aug-none
num_classes: 4
batch_size: 2
num_workers: 8
epochs: 15
seed: 42
include_bg_in_metric: false
device: cuda
optimizer:
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  name: rmsprop
scheduler:
  T_max: 35
  eta_min: 1.0e-06
  name: cosine
loss:
  lambda_dice: 1.0
  lambda_ce: 1.0
  to_onehot_y: true
  softmax: true
  gamma: 2.0
  focal_weight: null
  name: dice_ce
augmentations:
  name: none
